### ISSUE TITLE
 It's safe? 

### ISSUE THREAD

**Issue by AkioSarkiz** [stephenjude/laravel-wallet#3]
If parallel requests go to php, will the wallet work correctly? Reading the source code, I did not find such protection

**Comment by stephenjude** [comment]
@AkioSarkiz 

Parallel requests usually go through in most cases because someone is using multiple devices and one of the most straightforward solutions is to limit multi-device usage. 

The second option is that you take responsibility for handling concurrent requests. Check out this article, it will be of great help.

https://blog.tobexkee.com/handling-concurrency-attacks-in-laravel

**Comment by AkioSarkiz** [comment]
Thanks!
